package net.caprazzi.skimpy;

public enum ErrorCode {
	NO_ERROR, 
	ERR_CONFLICT_USER_EXISTS, 
	ERR_USER_WRONG_CREDENTIALS, 
	ERR_USER_NOT_CONFIRMED, 
	ERR_SERVER_ERROR, 
	ERR_NOT_FOUND,
	ERR_INVALID_ARGUMENTS,
	ERR_NOT_AUTORIZED
}


